### ISSUE TITLE
Add support for 32bit compilation

### ISSUE THREAD

**Issue by ejgallego** [gasche/opam-compiler-conf#7]
Hi, thanks for this script. I have a use case where I need to compile a 32bits ocaml from a 64 bits machine.

Using:

 ./configure --prefix $PREFIX -cc "gcc -m32" -as "as --32" -aspp "gcc -m32 -c" -host i386-linux -partialld "ld -r -melf_i386" -with-debug-runtime $*

as described in the OCAML readme works, but I dunno what is the best way to integrate with the script (add a switch, add configure32 command?)

Best regards,
E.

**Comment by gasche** [comment]
@ejgallego sorry for not answering for so long! `opam compiler-conf configure` will pass any command-line argument to the `./configure` script, so just running

```
opam compiler-conf configure --prefix $PREFIX -cc "gcc -m32" -as "as --32" -aspp "gcc -m32 -c" -host i386-linux -partialld "ld -r -melf_i386" -with-debug-runtime
```

should work. I'll close the issue, but any suggestion on how to document this better is welcome.

**Comment by ejgallego** [comment]
Seems good, thanks!
